from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import JSONResponse
from app.config import settings
import logging
from pydantic import BaseModel
from typing import List
from app.services.cache import cache_service

logger = logging.getLogger("uvicorn")

router = APIRouter(prefix="/api/ngrok", tags=["ngrok"])

class ManualTunnelRequest(BaseModel):
    public_url: str
    local_port: int = 8000
    protocol: str = "http"

@router.post("/add-manual-tunnel")
async def add_manual_tunnel(request: ManualTunnelRequest):
    """
    Add a manually created ngrok tunnel.
    This works by providing a URL generated by the ngrok CLI running locally.
    """
    try:
        # Validate URL format basic
        if not request.public_url.startswith('http'):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Invalid URL. Must start with http:// or https://"
            )

        # Store tunnel in cache (valid for 24 hours)
        # We use a set or a hash map for tunnels if we want multiple, but usually users just want one active
        tunnel_info = {
            "name": "Ngrok Tunnel",
            "public_url": request.public_url,
            "proto": request.protocol,
            "region": "manual"
        }
        
        # We use a specific pattern to find these later
        tunnel_key = f"ngrok:manual:{request.public_url}"
        await cache_service.set(tunnel_key, tunnel_info, expire=86400)

        return JSONResponse({
            "success": True,
            "tunnel": tunnel_info,
            "message": "Manual tunnel added successfully"
        })

    except HTTPException as e:
        raise e
    except Exception as e:
        logger.error(f"Failed to add manual tunnel: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to add manual tunnel: {str(e)}"
        )

@router.get("/tunnels")
async def list_ngrok_tunnels():
    """
    List all active manual ngrok tunnels from cache.
    """
    try:
        tunnel_list = []
        try:
            # Get all manual tunnel keys from Redis
            keys = await cache_service.redis.keys("ngrok:manual:*")
            for key in keys:
                tunnel_info = await cache_service.get(key)
                if tunnel_info:
                    tunnel_list.append(tunnel_info)
        except Exception as e:
            logger.warning(f"Failed to load manual tunnels from cache: {e}")

        return JSONResponse({
            "success": True,
            "tunnels": tunnel_list
        })

    except Exception as e:
        logger.error(f"Failed to list tunnels: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to list ngrok tunnels"
        )

@router.delete("/tunnels")
async def close_all_ngrok_tunnels():
    """
    Remove all manual tunnels from cache.
    """
    try:
        await cache_service.delete_pattern("ngrok:manual:*")
        return JSONResponse({
            "success": True,
            "message": "All manual tunnels removed"
        })
    except Exception as e:
        logger.error(f"Failed to clear tunnels: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to clear ngrok tunnels"
        )

@router.delete("/tunnels/{tunnel_name}")
async def close_ngrok_tunnel(tunnel_name: str):
    """
    Remove a specific manual tunnel from cache.
    """
    try:
        keys = await cache_service.redis.keys("ngrok:manual:*")
        for key in keys:
            tunnel_info = await cache_service.get(key)
            if tunnel_info and (tunnel_info['name'] == tunnel_name or tunnel_info['public_url'] == tunnel_name):
                await cache_service.delete(key)
                return JSONResponse({
                    "success": True,
                    "message": f"Tunnel {tunnel_name} removed"
                })

        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Tunnel {tunnel_name} not found"
        )
    except Exception as e:
        logger.error(f"Failed to remove tunnel: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to remove tunnel"
        )
