"""added db indexes for faster queries

Revision ID: 1ccf103e0998
Revises: c5c0eaf8722a
Create Date: 2026-02-10 07:20:26.558404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccf103e0998'
down_revision: Union[str, None] = 'c5c0eaf8722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_executions_journey_id'), 'executions', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journeys_spec_id'), 'journeys', ['spec_id'], unique=False)
    op.create_index(op.f('ix_journeys_user_id'), 'journeys', ['user_id'], unique=False)
    op.create_index(op.f('ix_specs_user_id'), 'specs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specs_user_id'), table_name='specs')
    op.drop_index(op.f('ix_journeys_user_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_spec_id'), table_name='journeys')
    op.drop_index(op.f('ix_executions_journey_id'), table_name='executions')
    # ### end Alembic commands ###
