"""added admin funtionality

Revision ID: c84de2f890e6
Revises: 1ccf103e0998
Create Date: 2026-02-23 00:03:23.106184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c84de2f890e6'
down_revision: Union[str, None] = '1ccf103e0998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_admin column with a default value first to avoid NOT NULL violation on existing rows
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")
    # Now set the column to NOT NULL
    op.alter_column('users', 'is_admin', nullable=False)
    
    # For specs table: ensure endpoints and schemas are not null
    # First update any null values to empty arrays/objects
    # op.execute("UPDATE specs SET endpoints = '[]'::json WHERE endpoints IS NULL")
    # op.execute("UPDATE specs SET schemas = '{}'::json WHERE schemas IS NULL")
    
    # # Now set the columns to NOT NULL (these should be fast after the updates)
    # op.alter_column('specs', 'endpoints',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            nullable=False)
    # op.alter_column('specs', 'schemas',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # op.alter_column('specs', 'schemas',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            nullable=True)
    # op.alter_column('specs', 'endpoints',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            nullable=True)
    # ### end Alembic commands ###
