"""added cascade for the joureys in the excution table

Revision ID: 0e2ab7f9b60c
Revises: d05e4fda10ab
Create Date: 2026-02-26 22:48:09.954697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2ab7f9b60c'
down_revision: Union[str, None] = 'd05e4fda10ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('executions_journey_id_fkey'), 'executions', type_='foreignkey')
    op.create_foreign_key(None, 'executions', 'journeys', ['journey_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.create_foreign_key(op.f('executions_journey_id_fkey'), 'executions', 'journeys', ['journey_id'], ['id'])
    # ### end Alembic commands ###