"""added cascade to db fk relationships

Revision ID: 46fdb59066ef
Revises: 0e2ab7f9b60c
Create Date: 2026-02-26 22:53:26.371032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fdb59066ef'
down_revision: Union[str, None] = '0e2ab7f9b60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('journeys_user_id_fkey'), 'journeys', type_='foreignkey')
    op.create_foreign_key(None, 'journeys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journeys', type_='foreignkey')
    op.create_foreign_key(op.f('journeys_user_id_fkey'), 'journeys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###