"""added sigup method for google auth

Revision ID: 4817d7956832
Revises: 46fdb59066ef
Create Date: 2026-03-29 00:56:01.176340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4817d7956832'
down_revision: Union[str, None] = '46fdb59066ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('journeys_spec_id_fkey'), 'journeys', type_='foreignkey')
    op.create_foreign_key(None, 'journeys', 'specs', ['spec_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('specs_user_id_fkey'), 'specs', type_='foreignkey')
    op.create_foreign_key(None, 'specs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Explicitly create the ENUM type first in PostgreSQL
    sign_up_enum = postgresql.ENUM('email', 'google', name='sign_up_method')
    sign_up_enum.create(op.get_bind(), checkfirst=True)
    
    # Add the column with a server_default so it doesn't error out on existing users
    op.add_column('users', sa.Column('sign_up_method', sa.Enum('email', 'google', name='sign_up_method'), nullable=True, server_default='email'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_up_method')
    
    # Explicitly drop the ENUM type during downgrade
    sign_up_enum = postgresql.ENUM('email', 'google', name='sign_up_method')
    sign_up_enum.drop(op.get_bind(), checkfirst=True)
    
    op.drop_constraint(None, 'specs', type_='foreignkey')
    op.create_foreign_key(op.f('specs_user_id_fkey'), 'specs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'journeys', type_='foreignkey')
    op.create_foreign_key(op.f('journeys_spec_id_fkey'), 'journeys', 'specs', ['spec_id'], ['id'])
    # ### end Alembic commands ###